version: '3.8'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    command:
      --replSet rs0

  devcontainer:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URI=mongodb://mongodb:27017/linkup
    volumes:
      - .:/workspace:cached
    network_mode: service:mongodb

volumes:
  mongodb_data:
